---
substitutions:
  device_name: athom-mini-3
  friendly_name: "Guest Bedroom Fan"
  area: "Guest Bedroom"
  static_ip: 192.168.7.84

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-fan.yaml
