---
substitutions:
  device_name: athom-mini-6
  friendly_name: "Basement SW 2"
  area: "Game Room"
  static_ip: 192.168.7.89

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-light.yaml
