---
substitutions:
  device_name: athom-mini-7
  friendly_name: "Basement SW 3"
  area: "Game Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.90
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
