---
substitutions:
  device_name: athom-mini-2
  friendly_name: "Isaac's Fan"
  area: "Isaac's Room"
  static_ip: 192.168.7.83

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-fan.yaml
