---
substitutions:
  device_name: athom-mini-7
  friendly_name: "Basement SW 3"
  area: "Game Room"
  static_ip: 192.168.7.90

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-light.yaml
