---
substitutions:
  device_name: athom-mini-9
  device_icon: "mdi:string-lights"
  friendly_name: "Deck String Lights"
  area: "Outside"
  static_ip: 192.168.7.95

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-light.yaml
