---
substitutions:
  device_name: athom-mini-1
  friendly_name: "Carson's Fan"
  area: "Carson's Room"
  static_ip: 192.168.7.82

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-fan.yaml
