---
substitutions:
  device_name: athom-mini-8
  friendly_name: "Deck Fan"
  area: "Outside"
  static_ip: 192.168.7.94

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-fan.yaml
