---
substitutions:
  device_name: athom-mini-4
  friendly_name: "Utility Room SW 2"
  area: "Utility Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-light.yaml
