---
substitutions:
  device_name: athom-mini-5
  friendly_name: "Basement SW 1"
  area: "Game Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-light.yaml

script:
  - id: !extend on_single
    then:
      - if:
          condition:
            lambda: 'return id(relay_light).current_values.is_on();'
          then:
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.mj_s01_29_basement_sw_4
          else:
            - homeassistant.service:
                service: light.turn_off
                data:
                  entity_id: light.mj_s01_29_basement_sw_4
