---
substitutions:
  device_name: athom-mini-9
  device_icon: "mdi:string-lights"
  friendly_name: "Deck String Lights"
  area: "Outside"

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.95
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
