---
substitutions:
  device_name: athom-mini-2
  friendly_name: "Isaac's Fan"
  area: "Isaac's Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-fan.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.83
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
