---
substitutions:
  device_name: athom-mini-3
  friendly_name: "Guest Bedroom Fan"
  area: "Guest Bedroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini.yaml
