---
substitutions:
  device_name: mj-st02-4
  friendly_name: "Upstairs Hall SW 1"
  area: "Upstairs Hall"
  static_ip: 192.168.7.45

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml
