---
substitutions:
  device_name: mj-s01-13
  friendly_name: "Master Bedroom SW 1"
  area: "Master Bedroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.54
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bedroom_light_1
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bedroom_light_2
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bedroom_light_3

  - id: !extend on_long
    then:
      - homeassistant.action:
          action: automation.trigger
          data:
            entity_id: automation.downstairs_off
      - script.execute: flash_purple
