---
substitutions:
  device_name: mj-s01-22
  friendly_name: "Living Room Switch 4"
  area: "Living Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
