---
substitutions:
  device_name: mj-s01-23
  friendly_name: "Living Room SW 5"
  area: "Outside"
  static_ip: 192.168.7.72

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_single
    then:
      - if:
          condition:
            lambda: 'return id(relay_light).current_values.is_on();'
          then:
            - homeassistant.action:
                action: light.turn_on
                data:
                  entity_id: light.mj_s01_33_garage_sw_1
          else:
            - homeassistant.action:
                action: light.turn_off
                data:
                  entity_id: light.mj_s01_33_garage_sw_1

  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.athom_mini_9_deck_string_lights

  - id: !extend on_long
    then:
      - homeassistant.action:
          action: fan.toggle
          data:
            entity_id: fan.athom_mini_8_deck_fan
      - script.execute: flash_purple
