---
substitutions:
  device_name: mj-s01-30
  friendly_name: "Basement SW 5"
  area: "Game Room"
  static_ip: 192.168.7.79
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml
