---
substitutions:
  device_name: mj-st02-4
  friendly_name: "Upstairs Hall SW 1"
  area: "Upstairs Hall"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.45
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
