substitutions:
  device_name: mj-s01-10
  friendly_name: "Guest Bedroom SW 1"
  area: "Guest Bedroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_long
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.downstairs_off
