---
substitutions:
  device_name: mj-s01-32
  friendly_name: "Basement SW 7"
  area: "Outside"
  static_ip: 192.168.7.81
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml
