---
substitutions:
  device_name: mj-s01-34
  friendly_name: "Utility Room SW 1"
  area: "Utility Room"
  click_short: 1ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_single
    then:
      - if:
          condition:
            lambda: 'return id(relay_light).current_values.is_on();'
          then:
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.athom_mini_4_utility_room_sw_2
          else:
            - homeassistant.service:
                service: light.turn_off
                data:
                  entity_id: light.athom_mini_4_utility_room_sw_2
