---
substitutions:
  device_name: mj-s01-5
  friendly_name: "Dining Room SW 1"
  area: "Dining Room"
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.46
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
