---
substitutions:
  device_name: mj-s01-33
  friendly_name: "Garage SW 1"
  area: "Outside"
  static_ip: 192.168.7.86

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.mj_st02_1_mud_room_sw_1
