---
substitutions:
  device_name: mj-s01-25
  friendly_name: "Basement Stairs SW 2"
  area: "Basement Stairs"
  light_auto_off_time: 15min

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml
