---
substitutions:
  device_name: mj-s01-32
  friendly_name: "Basement SW 7"
  area: "Outside"
  light_auto_off_time: 30min
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.81
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
