substitutions:
  device_name: mj-s01-1
  friendly_name: "Mud Room SW 2"
  area: "Entry"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.everything_off

  - id: !extend on_long
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.everything_off
