---
substitutions:
  device_name: mj-s01-20
  friendly_name: "Living Room SW 2"
  area: "Living Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
