---
substitutions:
  device_name: mj-s01-7
  friendly_name: "Carson Room SW 1"
  area: "Carson's Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.48
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.s31_7_carson_s_lights

  - id: !extend on_long
    then:
      - homeassistant.action:
          action: fan.toggle
          data:
            entity_id: fan.athom_mini_1_carson_s_fan
      - script.execute: flash_purple
