---
substitutions:
  device_name: mj-s01-32
  friendly_name: "Basement SW 7"
  area: "Outside"
  light_auto_off_time: 30min
  click_short: 1ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml
