---
substitutions:
  device_name: mj-s01-10
  friendly_name: "Guest Bedroom SW 1"
  area: "Guest Bedroom"
  light_auto_off_time: 10s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml

script:
  - id: !extend on_double
    then:
      - script.execute: light_timer
      - script.execute: flash_purple

  - id: !remove on_single
  - id: on_single
    then:
      - light.toggle: relay_light

  - id: !remove on_long
  - id: on_long
    then:
      - homeassistant.service:
          service: fan.toggle
          data:
            entity_id: fan.athom_mini_3_guest_bedroom_fan
