---
substitutions:
  device_name: mj-s01-1
  friendly_name: "Mud Room SW 2"
  area: "Entry"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.39
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.shelly_1_4_christmas_lights
      - script.execute: flash_purple
