---
substitutions:
  device_name: mj-st02-1
  friendly_name: "Mud Room SW 1"
  area: "Entry"
  static_ip: 192.168.7.38

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml
