---
substitutions:
  device_name: mj-s01-20
  friendly_name: "Living Room SW 2"
  area: "Living Room"
  static_ip: 192.168.7.69

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.accent_lights
