---
substitutions:
  device_name: mj-s01-14
  friendly_name: "Master Bedroom SW 2"
  area: "Master Bedroom"
  static_ip: 192.168.7.55
  fallback_ap_channel: "6"

packages:
  common: !include templates/common.yaml
  actions: !include templates/components/device-action.yaml
  device: !include templates/mj-s01-ceiling-fan.yaml

script:
  - id: !extend on_double
    then:
      - event.trigger:
          id: device_action
          event_type: double_click

  - id: !extend on_long
    then:
      - event.trigger:
          id: device_action
          event_type: long_press
      - script.execute: flash_purple
