---
substitutions:
  device_name: mj-st02-7
  friendly_name: "Basement Stairs SW 1"
  area: "Basement Stairs"
  static_ip: 192.168.7.66

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml
