---
substitutions:
  device_name: mj-s01-9
  friendly_name: "Upstairs Bathroom SW 2"
  area: "Upstairs Bathroom"
  fan_auto_off_time: 25min
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-bathroom-fan.yaml
