---
substitutions:
  device_name: mj-s01-25
  friendly_name: "Basement Stairs SW 2"
  area: "Basement Stairs"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_long
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.basement_off
      - script.execute: flash_purple
