---
substitutions:
  device_name: mj-s01-8
  friendly_name: "Upstairs Bathroom SW 1"
  area: "Upstairs Bathroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.kid_s_bedtime
      - script.execute: flash_purple
