---
substitutions:
  device_name: mj-s01-8
  friendly_name: "Upstairs Bathroom SW 1"
  area: "Upstairs Bathroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.s31_7_carson_s_lights
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.s31_9_isaac_s_lights
