---
substitutions:
  device_name: mj-s01-11
  friendly_name: "Laundry Room SW 1"
  area: "Laundry Room"
  static_ip: 192.168.7.52
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml
