---
substitutions:
  device_name: mj-s01-23
  friendly_name: "Living Room SW 5"
  area: "Outside"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_single
    then:
      - if:
          condition:
            lambda: 'return id(relay_light).current_values.is_on();'
          then:
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.mj_s01_33_garage_sw_1
          else:
            - homeassistant.service:
                service: light.turn_off
                data:
                  entity_id: light.mj_s01_33_garage_sw_1
  - id: !extend on_double
    then:
      - if:
          condition:
            lambda: 'return id(relay_light).current_values.is_on();'
          then:
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.mj_s01_33_garage_sw_1
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.mj_s01_32_basement_sw_7
          else:
            - homeassistant.service:
                service: light.turn_off
                data:
                  entity_id: light.mj_s01_33_garage_sw_1
            - homeassistant.service:
                service: light.turn_off
                data:
                  entity_id: light.mj_s01_32_basement_sw_7
