substitutions:
  device_name: mj-s01-8
  friendly_name: "Upstairs Bathroom SW 1"
  area: "Upstairs Bathroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01.yaml
