---
substitutions:
  device_name: mj-s01-33
  friendly_name: "Utility Room SW 1"
  area: "Utility Room"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
