---
substitutions:
  device_name: mj-s01-27
  friendly_name: "Basement Bathroom SW 1"
  area: "Basement Bathroom"
  light_auto_off_time: 30min
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml

api:
  reboot_timeout: 5min

wifi:
  manual_ip:
    static_ip: 192.168.7.76
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
  reboot_timeout: 5min
  output_power: 20.5dB
