---
substitutions:
  device_name: mj-s01-30
  friendly_name: "Basement SW 5"
  area: "Game Room"
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml

api:
  reboot_timeout: 5min

wifi:
  manual_ip:
    static_ip: 192.168.7.79
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
  reboot_timeout: 5min
  output_power: 20.5dB
