---
substitutions:
  device_name: mj-s01-31
  friendly_name: "Basement SW 6"
  area: "Basement"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
