---
substitutions:
  device_name: mj-s01-6
  friendly_name: "Isaac Room SW 1"
  area: "Isaac's Room"
  static_ip: 192.168.7.47

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.s31_2

  - id: !extend on_long
    then:
      - homeassistant.action:
          action: fan.toggle
          data:
            entity_id: fan.athom_mini_2_isaac_s_fan
      - script.execute: flash_purple
