---
substitutions:
  device_name: mj-s01-28
  friendly_name: "Basement Bathroom SW 2"
  area: "Basement Bathroom"
  static_ip: 192.168.7.77
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-bathroom-fan.yaml
