---
substitutions:
  device_name: mj-s01-8
  friendly_name: "Upstairs Bathroom SW 1"
  area: "Upstairs Bathroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.49
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: automation.trigger
          data:
            entity_id: automation.kid_s_bedtime
      - script.execute: flash_purple

  - id: !extend on_long
    then:
      - homeassistant.action:
          action: automation.trigger
          data:
            entity_id: automation.kid_s_bedtime
      - script.execute: flash_purple
