---
substitutions:
  device_name: mj-st02-6
  friendly_name: "Kitchen SW 1"
  area: "Kitchen"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.65
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
