---
substitutions:
  device_name: mj-s01-7
  friendly_name: "Carson Room SW 1"
  area: "Carson's Room"
  static_ip: 192.168.7.48

packages:
  common: !include templates/common.yaml
  actions: !include templates/components/device-action.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_double
    then:
      - event.trigger:
          id: device_action
          event_type: double_click

  - id: !extend on_long
    then:
      - if:
          condition:
            api.connected:
              state_subscription_only: true
          then:
            - event.trigger:
                id: device_action
                event_type: long_press
            - script.execute: flash_purple
          else:
            - script.execute: flash_action_error
