---
substitutions:
  device_name: mj-st02-6
  friendly_name: "Kitchen SW 1"
  area: "Kitchen"
  static_ip: 192.168.7.65

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml
