---
substitutions:
  device_name: mj-s01-25
  friendly_name: "Basement Stairs SW 2"
  area: "Basement Stairs"
  static_ip: 192.168.7.74

packages:
  common: !include templates/common.yaml
  actions: !include templates/components/device-action.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_single
    then:
      - if:
          condition:
            lambda: 'return id(relay_light).current_values.is_on();'
          then:
            - event.trigger:
                id: device_action
                event_type: relay_on
          else:
            - event.trigger:
                id: device_action
                event_type: relay_off

  - id: !extend on_long
    then:
      - event.trigger:
          id: device_action
          event_type: long_press
      # - script.execute: flash_purple

  - id: !extend on_double
    then:
      - event.trigger:
          id: device_action
          event_type: double_click
      - script.execute: flash_purple
