---
substitutions:
  device_name: mj-s01-9
  friendly_name: "Upstairs Bathroom SW 2"
  area: "Upstairs Bathroom"
  static_ip: 192.168.7.50
  fan_auto_off_time: 30min
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-bathroom-fan.yaml
