---
substitutions:
  device_name: mj-s01-12
  friendly_name: "Laundry Room SW 2"
  area: "Laundry Room"
  static_ip: 192.168.7.53
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-bathroom-fan.yaml
