---
substitutions:
  device_name: mj-s01-1
  friendly_name: "Mud Room SW 2"
  area: "Entry"
  static_ip: 192.168.7.39

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.shelly_1_4_christmas_lights
      - script.execute: flash_purple
