---
substitutions:
  device_name: mj-st02-3
  friendly_name: "Entry SW 2"
  area: "Entry"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.44
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
