---
substitutions:
  device_name: mj-s01-29
  friendly_name: "Basement SW 4"
  area: "Game Room"
  static_ip: 192.168.7.78
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
