---
substitutions:
  device_name: mj-s01-25
  friendly_name: "Basement Stairs SW 2"
  area: "Basement Stairs"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_single
    then:
      - if:
          condition:
            lambda: 'return id(relay_light).current_values.is_on();'
          then:
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.mj_s01_34_utility_room_sw_1
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.athom_mini_4_utility_room_sw_2
          else:
            - homeassistant.service:
                service: light.turn_off
                data:
                  entity_id: light.mj_s01_34_utility_room_sw_1
            - homeassistant.service:
                service: light.turn_off
                data:
                  entity_id: light.athom_mini_4_utility_room_sw_2

  - id: !extend on_long
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.basement_off
