substitutions:
  device_name: mj-s01-15
  friendly_name: "Master Bathroom SW 1"
  area: "Master Bathroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
