---
substitutions:
  device_name: mj-st02-3
  friendly_name: "Entry SW 2"
  area: "Entry"
  static_ip: 192.168.7.44

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml
