---
substitutions:
  device_name: mj-s01-18
  friendly_name: "Master Closet SW 1"
  area: "Master Closet"
  light_auto_off_time: 15min
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml
