---
substitutions:
  device_name: mj-s01-4
  friendly_name: "Sitting Room SW 1"
  area: "Sitting Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.basement_off
      - homeassistant.service:
          service: light.turn_off
          data:
            entity_id: light.mj_st02_7_basement_stairs_sw_1
      - script.execute: flash_purple

  - id: !extend on_long
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.upstairs_off
      - script.execute: flash_purple
