---
substitutions:
  device_name: mj-s01-25
  friendly_name: "Basement Stairs SW 2"
  area: "Basement Stairs"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_long
    then:
      - homeassistant.service:
          service: light.turn_off
          data:
            area_id: basement
      - homeassistant.service:
          service: light.turn_off
          data:
            area_id: basement_bathroom
      - homeassistant.service:
          service: light.turn_off
          data:
            area_id: utility_room
      - homeassistant.service:
          service: light.turn_off
          data:
            entity_id: light.mj_st02_7_basement_stairs_sw_1
      - homeassistant.service:
          service: fan.turn_off
          data:
            area_id: basement_bathroom
      - script.execute: flash_purple
