---
substitutions:
  device_name: mj-s01-2
  friendly_name: "Main Bathroom SW 1"
  area: "Main Bathroom"
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.40
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
