substitutions:
  device_name: mj-s01-2
  friendly_name: "Main Bathroom SW 1"
  area: "Main Bathroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
