---
substitutions:
  device_name: mj-s01-11
  friendly_name: "Laundry Room SW 1"
  area: "Upstairs Hall"
  light_auto_off_time: 30min

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml
