---
substitutions:
  device_name: mj-s01-4
  friendly_name: "Sitting Room SW 1"
  area: "Sitting Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.42
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: automation.trigger
          data:
            entity_id: automation.basement_off
      - homeassistant.action:
          action: light.turn_off
          data:
            entity_id: light.mj_st02_7_basement_stairs_sw_1
      - script.execute: flash_purple

  - id: !extend on_long
    then:
      - homeassistant.action:
          action: automation.trigger
          data:
            entity_id: automation.upstairs_off
      - script.execute: flash_purple
