---
substitutions:
  device_name: mj-s01-6
  friendly_name: "Isaac Room SW 1"
  area: "Isaac's Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.s31_9_isaac_s_lights
      - script.execute: flash_purple
