---
substitutions:
  device_name: mj-s01-24
  friendly_name: "Kitchen SW 2"
  area: "Kitchen"
  click_short: 1ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
