---
substitutions:
  device_name: mj-s01-17
  friendly_name: "Master Bathroom SW 3"
  area: "Master Bathroom"
  fan_auto_off_time: 25min
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-bathroom-fan.yaml
