substitutions:
  device_name: mj-s01-15
  friendly_name: "Master Bathroom SW 1"
  area: "Master Bathroom"
  light_auto_off_time: 30min

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml
