substitutions:
  device_name: mj-s01-10
  friendly_name: "Guest Bedroom SW 1"
  area: "Guest Bedroom"
  light_auto_off_time: 10s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: light_timer
    then:
      - light.turn_on: red_led
      - light.turn_on: relay_light
      - delay: $light_auto_off_time
      - light.turn_off: red_led
      - light.turn_off: relay_light

  - id: !extend on_double
    then:
      - if:
          condition:
            light.is_on: relay_light
          then:
            - script.stop: light_timer
            - light.turn_off: red_led
            - light.turn_off: relay_light
          else:
            - script.stop: light_timer
            - script.execute: light_timer

  - id: !extend on_single
    then:
      - script.stop: light_timer
      - light.turn_off: red_led

  - id: !extend on_long
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.automatic_bedtime

