---
substitutions:
  device_name: mj-st02-5
  friendly_name: "Living Room SW 1"
  area: "Living Room"
  static_ip: 192.168.7.64

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml
