---
substitutions:
  device_name: mj-s01-27
  friendly_name: "Basement Bathroom SW 1"
  area: "Basement Bathroom"
  static_ip: 192.168.7.76
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml
