---
substitutions:
  device_name: mj-s01-22
  friendly_name: "Living Room SW 4"
  area: "Living Room"
  static_ip: 192.168.7.71

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.living_room_light_1
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.living_room_light_2
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.wled_2
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.mj_s01_24_kitchen_sw_2
