---
substitutions:
  device_name: mj-s01-14
  friendly_name: "Master Bedroom SW 2"
  area: "Master Bedroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-ceiling-fan.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.bedroom_light_1
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.bedroom_light_2
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: light.bedroom_light_3
      - script.execute: flash_purple

  - id: !extend on_long
    then:
      - homeassistant.service:
          service: automation.trigger
          data:
            entity_id: automation.automatic_bedtime
      - script.execute: flash_purple
