---
substitutions:
  device_name: mj-s01-31
  friendly_name: "Basement SW 6"
  area: "Game Room"
  click_short: 1ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
