---
substitutions:
  device_name: mj-s01-33
  friendly_name: "Garage SW 1"
  area: "Outside"
  light_auto_off_time: 15min

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light-auto.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.86
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.mj_st02_1_mud_room_sw_1
