---
substitutions:
  device_name: mj-s01-21
  friendly_name: "Living Room Switch 3"
  area: "Living Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-ceiling-fan.yaml
