---
substitutions:
  device_name: mj-s01-17
  friendly_name: "Master Bathroom SW 3"
  area: "Master Bathroom"
  fan_auto_off_time: 25min
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-bathroom-fan.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.58
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
