---
substitutions:
  device_name: mj-s01-8
  friendly_name: "Upstairs Bathroom SW 1"
  area: "Upstairs Bathroom"
  static_ip: 192.168.7.49
  fallback_ap_channel: "6"
  button_template: components/mj-s01-button-single.yaml

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
