---
substitutions:
  device_name: mj-st02-2
  friendly_name: "Entry SW 1"
  area: "Entry"
  static_ip: 192.168.7.43

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml
