---
substitutions:
  device_name: s31-6
  friendly_name: "Bedroom Light 3"
  area: "Master Bedroom"
  static_ip: 192.168.7.16

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml

script:
  - id: !extend on_double
    then:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bedroom_light_1
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.bedroom_light_2
#      - homeassistant.action:
#          action: light.toggle
#          data:
#            entity_id: light.bedroom_light_3

  - id: !extend on_long
    then:
      - homeassistant.action:
          action: automation.trigger
          data:
            entity_id: automation.bedtime
      - script.execute: flash_blue
