---
substitutions:
  device_name: s31-7
  device_icon: "mdi:string-lights"
  friendly_name: "Carson's Lights"
  area: "Carson's Room"
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
