substitutions:
  device_name: s31-7
  device_icon: "mdi:string-lights"
  friendly_name: "Carson's Lights"

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
