---
substitutions:
  device_name: s31-9
  device_icon: "mdi:popcorn"
  friendly_name: "Popcorn Popper"
  area: "Dining Room"
  static_ip: 192.168.7.26
  button_template: components/s31-button-single.yaml

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
