---
substitutions:
  device_name: s31-10
  friendly_name: "Living Room Light 1"
  area: "Living Room"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
