---
substitutions:
  device_name: s31-11
  friendly_name: "Living Room Light 2"
  area: "Living Room"
  button_template: components/s31-button-single.yaml
  static_ip: 192.168.7.28

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
