---
substitutions:
  device_name: s31-3
  friendly_name: "Garage Power Strip"
  area: "Garage"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-switch.yaml
