---
substitutions:
  device_name: s31-10
  friendly_name: "Living Room Light 1"
  area: "Living Room"
  static_ip: 192.168.7.27
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
