---
substitutions:
  device_name: s31-3
  friendly_name: "Garage Power Strip"
  area: "Garage"
  static_ip: 192.168.7.13
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-switch.yaml
