---
substitutions:
  device_name: s31-9
  device_icon: "mdi:string-lights"
  friendly_name: "Isaac's Lights"
  area: "Isaac's Room"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
