---
substitutions:
  device_name: s31-11
  friendly_name: "Living Room Light 2"
  area: "Living Room"
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.28
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
