substitutions:
  device_name: s31-10
  device_icon: "mdi:lamp"
  friendly_name: "Living Room Light 1"
  area: "Living Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
