---
substitutions:
  device_name: s31-1
  device_icon: "mdi:lamp"
  friendly_name: "Carson's Lamp"
  area: "Carson's Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-light.yaml
