substitutions:
  device_name: s31-6
  device_icon: "mdi:lamp"
  friendly_name: "Bedroom Light 3"
  area: "Master Bedroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
