# Sonoff S31 Configuration
esphome:
  name: s31-2

esp8266:
  board: esp8285

# Enable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: "8fe03ffa7cf3b0e595c9510b7da732a4"

time:
  - platform: homeassistant
    id: ha_time
    timezone: America/Chicago

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  domain: .iot.tacomafia.net
  power_save_mode: LIGHT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S31-2 Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Basic Configuration - https://www.esphome-devices.com/devices/Sonoff-S31

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Light 2 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Light 2 Switch"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: true

sensor:
  - platform: cse7766
    power:
      name: "Light 2 Power"
    energy:
      name: "Light 2 Energy"
