---
substitutions:
  device_name: shelly-1-4
  device_icon: "mdi:string-lights"
  friendly_name: "Christmas Lights"
  area: "Front Porch"

packages:
  common: !include templates/common.yaml
  device: !include templates/shelly-1-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.24
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
