substitutions:
  device_name: shelly-1-4
  friendly_name: "Christmas Lights"
  area: "Front Porch"

packages:
  common: !include templates/common.yaml

# Basic configuration - https://www.esphome-devices.com/devices/Shelly-1

esp8266:
  board: esp01_1m
  restore_from_flash: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
    id: relay_button
    on_press:
      then:
        - light.toggle: relay_light
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: restart_button

light:
  - platform: binary
    name: None
    icon: "mdi:string-lights"
    id: relay_light
    output: relay_output
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: gpio
    pin: GPIO4
    id: relay_output
