substitutions:
  device_name: shelly-plus1pm-1
  friendly_name: "Guest Bedroom Fan"
  area: "Guest Bedroom"

packages:
  common: !include templates/common.yaml
  device: !include templates/shelly-plus1pm-fan.yaml
