---
# Shelly EM
# - https://www.esphome-devices.com/devices/Shelly-EM
# - https://templates.blakadder.com/shelly_EM.html

substitutions:
  device_name: shelly-em
  friendly_name: "Shelly EM"
  area: "Utility Room"
  static_ip: 192.168.7.19
  sample_rate: "1s"
  update_interval_fast: "15s"
  update_interval_slow: "60s"

  # 120A clamp (3000:1): 1.143207411 - https://community.home-assistant.io/t/anyone-using-shelly-em/149867/14
  # Phase 2 derived from 20 samples from Shelly 1 Plus PM on Fridge: 1.1059
  scale_a_power: '1.1059'
  scale_b_power: '1.1059'

packages:
  common: !include templates/common.yaml

esp8266:
  board: esp01_1m

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ade7953_i2c
    irq_pin: GPIO13
    update_interval: $sample_rate
    use_accumulated_energy_registers: true
    voltage:
      name: Voltage
      id: voltage
      filters:
        - throttle_average: $update_interval_slow
        - delta: 0.2
    current_a:
      name: Phase 1 Current
      id: current_phase_1
      filters:
        - or:
          - delta: 0.1
          - throttle_average: $update_interval_fast
        - delta: 0.05
    current_b:
      name: Phase 2 Current
      id: current_phase_2
      filters:
        - or:
          - delta: 0.1
          - throttle_average: $update_interval_fast
        - delta: 0.05
    active_power_a:
      name: Phase 1 Power
      id: power_phase_1
      filters:
        - multiply: $scale_a_power
        - or:
          - delta: 10.0
          - throttle_average: $update_interval_fast
        - delta: 5.0
      on_value:
        - component.update: total_power
    active_power_b:
      name: Phase 2 Power
      id: power_phase_2
      filters:
        - multiply: $scale_b_power
        - or:
          - delta: 10.0
          - throttle_average: $update_interval_fast
        - delta: 5.0
      on_value:
        - component.update: total_power

  - platform: template
    name: Total Power
    id: total_power
    state_class: measurement
    device_class: power
    unit_of_measurement: W
    lambda: return id(power_phase_1).state + id(power_phase_2).state;
    update_interval: never

  - platform: total_daily_energy
    name: Phase 1 Daily Energy
    id: energy_phase_1
    power_id: power_phase_1
    method: trapezoid
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
      - throttle: $update_interval_slow
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: Phase 2 Daily Energy
    id: energy_phase_2
    power_id: power_phase_2
    method: trapezoid
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
      - throttle: $update_interval_slow
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: Total Daily Energy
    id: total_energy
    power_id: total_power
    method: trapezoid
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
      - throttle: $update_interval_slow
    unit_of_measurement: kWh

status_led:
  pin:
    number: GPIO0
    inverted: yes
