---
# Shelly EM
# - https://www.esphome-devices.com/devices/Shelly-EM
# - https://templates.blakadder.com/shelly_EM.html

substitutions:
  device_name: shelly-em
  friendly_name: "Shelly EM"
  area: "Utility Room"
  sample_rate: "1s"
  update_interval_fast: "15s"
  update_interval_slow: "60s"

  # 120A clamp (3000:1): 1.143207411
  # 50A clamp (2400:1): 1.156612516
  # 50A Victron clamp (2000:1): 0.76
  # Derived from Evergy bill: 1.102413
  scale_a_power: '1.143207411'
  scale_b_power: '1.143207411'

packages:
  common: !include templates/common.yaml

esp8266:
  board: esp01_1m

logger:
  level: INFO

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ade7953_i2c
    irq_pin: GPIO13
    voltage:
      name: Voltage
      id: voltage
      filters:
        - or:
          - delta: 1%
          - throttle_average: $update_interval_slow
    frequency:
      name: Frequency
      id: frequency
      filters:
          - throttle: $update_interval_slow
    current_a:
      name: Phase 1 Current
      id: current_phase_1
      filters:
        - or:
          - delta: 10%
          - throttle_average: $update_interval_fast
    current_b:
      name: Phase 2 Current
      id: current_phase_2
      filters:
        - or:
          - delta: 10%
          - throttle_average: $update_interval_fast
    active_power_a:
      name: Phase 1 Power
      id: power_phase_1
      filters:
        - multiply: $scale_a_power
        - or:
          - delta: 10%
          - throttle_average: $update_interval_fast
    active_power_b:
      name: Phase 2 Power
      id: power_phase_2
      filters:
        - multiply: $scale_b_power
        - or:
          - delta: 10%
          - throttle_average: $update_interval_fast
    apparent_power_a:
      name: Phase 1 Apparent Power
      id: apparent_power_phase_1
      filters:
        - multiply: $scale_a_power
        - or:
          - delta: 10%
          - throttle_average: $update_interval_fast
    apparent_power_b:
      name: Phase 2 Apparent Power
      id: apparent_power_phase_2
      filters:
        - multiply: $scale_b_power
        - or:
          - delta: 10%
          - throttle_average: $update_interval_fast
    power_factor_a:
      name: Phase 1 Power Factor
      id: power_factor_phase_1
      filters:
        - throttle_average: $update_interval_fast
    power_factor_b:
      name: Phase 2 Power Factor
      id: power_factor_phase_2
      filters:
        - throttle_average: $update_interval_fast
    reactive_power_a:
      name: Phase 1 Reactive Power
      id: reactive_power_phase_1
      filters:
        - multiply: $scale_a_power
        - or:
          - delta: 10%
          - throttle_average: $update_interval_fast
    reactive_power_b:
      name: Phase 2 Reactive Power
      id: reactive_power_phase_2
      filters:
        - multiply: $scale_b_power
        - or:
          - delta: 10%
          - throttle_average: $update_interval_fast
    update_interval: $sample_rate

  - platform: template
    name: Total Power
    id: total_power
    state_class: measurement
    device_class: power
    lambda: return id(power_phase_1).state + id(power_phase_2).state;
    unit_of_measurement: W
    filters:
      - or:
        - delta: 10%
        - throttle_average: $update_interval_fast
    update_interval: $sample_rate

  - platform: total_daily_energy
    name: Phase 1 Daily Energy
    id: energy_phase_1
    power_id: power_phase_1
    filters:
      - multiply: 0.001
      - throttle: $update_interval_slow
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: Phase 2 Daily Energy
    id: energy_phase_2
    power_id: power_phase_2
    filters:
      - multiply: 0.001
      - throttle: $update_interval_slow
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: Total Daily Energy
    id: total_energy
    power_id: total_power
    filters:
      - multiply: 0.001
      - throttle: $update_interval_slow
    unit_of_measurement: kWh

  - platform: ntc
    sensor: temp_resistance_reading
    name: "Temperature"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    # This value is a guess, based on the temperature values compared to native Shelly EM devices
    resistor: 100kOhm

  - platform: adc
    id: temp_analog_reading
    pin: A0

status_led:
  pin:
    number: GPIO0
    inverted: yes

switch:
  - platform: gpio
    name: Switch
    pin: GPIO15
    id: relay_switch
