---
substitutions:
  device_name: shelly-1-1
  friendly_name: "Kim's Garage Door"
  area: "Garage"

packages:
  common: !include templates/common.yaml
  device: !include templates/shelly-1-garage-door.yaml
