substitutions:
  device_name: shelly-s1-4
  friendly_name: "shelly-s1-4"

packages:
  common: !include common/common.yaml

# Device-specific config
esp8266:
  board: esp01_1m

# Enable logging
logger:

# Basic configuration - https://www.esphome-devices.com/devices/Shelly-1

# Device Specific Config
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      #mode:
        #input: true
        #pullup: true
      #inverted: true
    on_state:
      then:
        - switch.toggle: relay
    id: sw_input

switch:
  - platform: gpio
    name: $friendly_name Switch
    pin: GPIO4
    id: relay