---
substitutions:
  device_name: shelly-1-2
  friendly_name: "Kyle's Garage Door"
  area: "Garage"

packages:
  common: !include templates/common.yaml
  device: !include templates/shelly-1-garage-door.yaml
