substitutions:
  device_name: shelly-s1-4
  friendly_name: "Porch Outlet"

packages:
  common: !include templates/common.yaml

# Basic configuration - https://www.esphome-devices.com/devices/Shelly-1

esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: $friendly_name Button
    on_state:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    name: $friendly_name Switch
    pin: GPIO4
    id: relay
