---
substitutions:
  device_name: shelly-1-3
  friendly_name: "Third Car Garage Door"
  area: "Garage"

packages:
  common: !include templates/common.yaml
  device: !include templates/shelly-1-garage-door.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.23
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
