---
substitutions:
  device_name: shelly-1-4
  device_icon: "mdi:string-lights"
  friendly_name: "Christmas Lights"
  area: "Front Porch"
  static_ip: 192.168.7.24

packages:
  common: !include templates/common.yaml
  device: !include templates/shelly-1-light.yaml
