---
substitutions:
  device_name: shelly-1-3
  friendly_name: "Third Car Garage Door"
  area: "Garage"
  static_ip: 192.168.7.23

packages:
  common: !include templates/common.yaml
  device: !include templates/shelly-1-garage-door.yaml
