substitutions:
  device_name: shelly-s1-4
  friendly_name: "Porch Outlet"

packages:
  common: !include templates/common.yaml

# Basic configuration - https://www.esphome-devices.com/devices/Shelly-1

esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
    name: $friendly_name Button
    on_state:
      then:
        - switch.toggle: relay
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: restart_button

switch:
  - platform: gpio
    name: $friendly_name Switch
    pin: GPIO4
    id: relay
