---
substitutions:
  device_name: shelly-plus1pm-2
  friendly_name: "Isaac's Fan"
  area: "Isaac's Room"

packages:
  common: !include templates/common.yaml
  device: !include templates/shelly-plus1pm-fan.yaml
