---
substitutions:
  device_name: athom-mini-10
  friendly_name: "Athom Mini 10"
  area: "Outside"
  static_ip: 192.168.7.96

packages:
  common: !include templates/common.yaml
  device: !include templates/athom-mini-light.yaml
