---
substitutions:
  device_name: mj-s01-26
  friendly_name: "Basement SW 1"
  area: "Game Room"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
