---
substitutions:
  device_name: mj-st02-8
  friendly_name: "Basement SW 2"
  area: "Game Room"
  static_ip: 192.168.7.67

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-st02.yaml
