---
substitutions:
  device_name: mj-s01-35
  friendly_name: "Utility Room SW 2"
  area: "Utility Room"
  click_short: 1ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
