---
substitutions:
  device_name: mj-s01-26
  friendly_name: "Basement SW 1"
  area: "Game Room"
  static_ip: 192.168.7.75
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/mj-s01-light.yaml
