---
substitutions:
  device_name: s31-2
  friendly_name: "Isaac's Lamp"
  area: "Isaac's Room"
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.12
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
