---
substitutions:
  device_name: s31-7
  device_icon: "mdi:string-lights"
  friendly_name: "Carson's Lights"
  area: "Carson's Room"
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.17
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
