---
substitutions:
  device_name: s31-8
  device_icon: "mdi:floor-lamp"
  friendly_name: "Basement Light"
  area: "Game Room"
  static_ip: 192.168.7.25
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
