---
substitutions:
  device_name: s31-1
  friendly_name: "Carson's Lamp"
  area: "Carson's Room"
  static_ip: 192.168.7.11
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-light.yaml
