---
substitutions:
  device_name: s31-1
  friendly_name: "Carson's Lamp"
  area: "Carson's Room"
  click_short: 0s

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-light.yaml
