---
substitutions:
  device_name: s31-9
  device_icon: "mdi:string-lights"
  friendly_name: "Isaac's Lights"
  area: "Isaac's Room"
  static_ip: 192.168.7.26
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml
