---
substitutions:
  device_name: s31-8
  device_icon: "mdi:floor-lamp"
  friendly_name: "Basement Light"
  area: "Game Room"
  click_short: 25ms

packages:
  common: !include templates/common.yaml
  device: !include templates/s31-lite-light.yaml

wifi:
  manual_ip:
    static_ip: 192.168.7.25
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1
