# Sonoff S31 Lite - https://www.esphome-devices.com/devices/Sonoff-S31
esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: $friendly_name Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: $friendly_name Switch
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: true
