# Common configuration for all devices
esphome:
  name: $device_name
  comment: $friendly_name

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Enable OTAs
ota:
  password: !secret ota_password

# Sync RTC with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago

# Wi-Fi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  domain: .iot.tacomafia.net
  power_save_mode: LIGHT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_name Recovery
    password: !secret ap_password
    channel: 6

captive_portal:
