---
# Athom Mini Switch
# - https://github.com/athom-tech/athom-configs/blob/main/athom-mini-switch.yaml
esp8266:
  board: esp8285
  restore_from_flash: true

script:
  - id: on_single
    then: {}

  - id: on_long
    then:
      - button.press: restart_button

output:
  - platform: gpio
    id: relay_output
    pin: GPIO13

binary_sensor:
  - platform: gpio
    id: the_switch
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: restart_button

  - platform: gpio
    id: the_button
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - script.execute: on_single
      - timing:
          - ON for at least 4s
        then:
          - script.execute: on_long

light:
  - platform: status_led
    id: led
    pin:
      number: GPIO4
      inverted: true
