---
# Athom Mini Switch
# - https://github.com/athom-tech/athom-configs/blob/main/athom-mini-switch.yaml
# - https://www.espthings.io/index.php/2021/10/30/athom-mini-relay-switch-esphome/
esp8266:
  board: esp8285
  restore_from_flash: true
  early_pin_init: false

script:
  - id: on_single
    then: {}

output:
  - platform: gpio
    id: relay_output
    pin: GPIO13

  - platform: gpio
    id: led_output
    pin:
      number: GPIO4
      inverted: true

binary_sensor:
  - platform: gpio
    id: the_switch
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
    on_state:
      then:
        - script.execute: on_single

  - platform: gpio
    id: the_button
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
      inverted: true
    on_click:
        then:
          - script.execute: on_single

light:
  - platform: binary
    id: led
    output: led_output
