---
# Athom Mini Switch
# - https://github.com/athom-tech/athom-configs/blob/main/athom-mini-switch.yaml
esp8266:
  board: esp8285

output:
  - platform: gpio
    id: relay_output
    pin: GPIO13

binary_sensor:
  # Wired switch
  - platform: gpio
    id: the_switch
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
    on_state:
      - light.toggle: relay_light
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: restart_button

  # Button on mini switch
  - platform: gpio
    id: the_button
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: relay_light
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button

light:
  - platform: binary
    id: relay_light
    name: None
    output: relay_output
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

  - platform: status_led
    id: led
    pin:
      number: GPIO4
      inverted: true
