---
# Athom Mini Switch - Light
packages:
  parent: !include athom-mini-base.yaml

binary_sensor:
  - id: !extend the_switch
    on_click:
      - light.toggle: relay_light

script:
  - id: !extend on_single
    then:
      - light.toggle: relay_light

light:
  - platform: binary
    id: relay_light
    name: None
    output: relay_output
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led
    restore_mode: RESTORE_DEFAULT_OFF
