# Common configuration for all devices
esphome:
  name: $device_name
  friendly_name: $friendly_name
  area: $area

logger:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    timezone: America/Chicago

#network:
#  enable_ipv6: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  domain: .iot.tacomafia.net
#  power_save_mode: LIGHT

  ap:
    password: !secret ap_password
    channel: 6

captive_portal:

#sensor:
#  - platform: wifi_signal
#    name: WiFi Signal
#    update_interval: 60s
#  - platform: uptime
#    name: Uptime
#binary_sensor:
#  - platform: status
#    name: Status
#text_sensor:
#  - platform: wifi_info
#    ip_address:
#      name: IP Address
#    ssid:
#      name: Connected SSID
#    mac_address:
#      name: Mac Address

button:
  - platform: restart
    id: restart_button
    name: Restart
#  - platform: factory_reset
#    id: reset_button
#    name: Factory Reset
