# Common configuration for all devices
esphome:
  name: $device_name
  comment: $friendly_name

# Enable logging
logger:

# Enable HA API
api:
  password: !secret api_password
  encryption:
    key: !secret api_key

# Enable OTAs
ota:
  password: !secret api_password

# Sync RTC with HA
time:
  - platform: homeassistant
    timezone: America/Chicago

# Wi-Fi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  domain: .iot.tacomafia.net
  power_save_mode: LIGHT

  # Enable fallback hotspot (captive portal) in case Wi-Fi connection fails
  ap:
    password: !secret ap_password
    channel: 6

captive_portal:

# Generic sensors to report status to HA
#sensor:
#  - platform: wifi_signal
#    name: $friendly_name WiFi Signal
#  - platform: uptime
#    name: $friendly_name Uptime
#binary_sensor:
#  - platform: status
#    name: $friendly_name Status

# Generic button to remotely restart device from HA
button:
  - platform: restart
    id: restart_button
    name: $friendly_name Restart
