---
# Common configuration for all devices
esphome:
  name: $device_name
  friendly_name: $friendly_name
  area: $area

logger:

api:
  reboot_timeout: 60min
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time
    timezone: America/Chicago

network:
  enable_ipv6: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .iot.tacomafia.net
  power_save_mode: LIGHT
  reboot_timeout: 15min

#  ap:
#    password: !secret ap_password
#    ap_timeout: 5min
#
#captive_portal:

button:
  - platform: restart
    id: restart_button
    name: Restart
#  - platform: factory_reset
#    id: reset_button
#    name: Factory Reset

#sensor:
#  - platform: wifi_signal
#    name: WiFi Signal
#    update_interval: 60s
#  - platform: uptime
#    name: Uptime

#binary_sensor:
#  - platform: status
#    name: Status

#text_sensor:
#  - platform: version
#    name: "ESPHome Version"
#  - platform: wifi_info
#    ip_address:
#      name: IP Address
#      address_0:
#        name: IP Address 0
#      address_1:
#        name: IP Address 1
#      address_2:
#        name: IP Address 2
#      address_3:
#        name: IP Address 3
#      address_4:
#        name: IP Address 4
#    ssid:
#      name: Connected SSID
#    mac_address:
#      name: MAC Address
