---
# Common configuration for all devices
esphome:
  name: $device_name
  friendly_name: $friendly_name
  area: $area

logger:
  baud_rate: 0
  level: INFO

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time
    timezone: America/Chicago
    update_interval: 6h

#network:
#  enable_ipv6: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .iot.tacomafia.net
  power_save_mode: LIGHT
  min_auth_mode: WPA2

  ap:
    password: !secret ap_password
    ap_timeout: 10min

  manual_ip:
    static_ip: $static_ip
    gateway: 192.168.7.1
    subnet: 255.255.255.0
    dns1: 192.168.7.1

captive_portal:

button:
  - platform: restart
    id: restart_button
    name: Restart

sensor:
  - platform: uptime
    name: Uptime
    entity_category: diagnostic

  - platform: wifi_signal
    name: WiFi Signal
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    bssid:
      name: WiFi BSSID
    scan_results:
      name: WiFi Latest Scan Results
    power_save_mode:
      name: WiFi Power Save Mode
