# Garage Door Opener - https://savjee.be/2020/06/make-garage-door-opener-smart-shelly-esphome-home-assistant/
esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin: GPIO5
    id: contact_sensor
    filters:
      - invert:
      # Debounce the contact sensor to prevent rapid on/off/on events
      - delayed_on_off: 500ms

switch:
  - platform: gpio
    pin: GPIO4
    id: relay

cover:
  - platform: template
    device_class: garage
    name: $friendly_name
    lambda: |-
      if (id(contact_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - script.execute: toggle_cover
    close_action:
      - script.execute: toggle_cover
    stop_action:
      - script.execute: toggle_cover

script:
  - id: toggle_cover
    then:
      - switch.turn_on: relay
      - delay: 250ms
      - switch.turn_off: relay
