# Garage Door Opener
# - https://savjee.be/2020/06/make-garage-door-opener-smart-shelly-esphome-home-assistant/
# - https://github.com/athom-tech/athom-configs/blob/main/athom-garage-door.yaml
esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    id: contact
    pin:
      number: GPIO5
      mode:
        input: true
      inverted: true
    filters:
      # Debounce the contact sensor to prevent rapid on/off/on events
      - delayed_on_off: 20ms

switch:
  - platform: gpio
    id: relay_switch
    pin: GPIO4
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_switch

cover:
  - platform: template
    name: None
    device_class: garage
    lambda: "return id(contact).state ? COVER_OPEN : COVER_CLOSED;"
    open_action:
      - switch.turn_on: relay_switch
    close_action:
      - switch.turn_on: relay_switch
    stop_action:
      - switch.turn_on: relay_switch
