---
# Martin Jerry MJ-ST02 3-Way Switch
# - https://esphome.io/components/tuya.html
# - https://community.home-assistant.io/t/martin-jerry-st02-3-way-tasmota-switch/536416
# - https://github.com/joshuaboniface/martinjerry-esphome/blob/master/mj-st02/mj-st02.yaml
substitutions:
  device_icon: "mdi:lightbulb"

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false

logger:
  baud_rate: 0
  level: INFO

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Tuya Datapoint 1: switch
# Tuya Datapoint 7: int value: 0
tuya:
  time_id: ha_time

light:
  - platform: tuya
    name: None
    icon: $device_icon
    switch_datapoint: 1
    restore_mode: RESTORE_DEFAULT_OFF
