# Martin Jerry MJ-S01 Wall Switch (Fan)
# - https://digiblur.com/wiki/devices/switches/martin_jerry_mj-s01_single_pole
# - https://devices.esphome.io/devices/MJ-S01
esp8266:
  board: esp01_1m

output:
  - platform: gpio
    id: relay_output
    pin: GPIO12

  - platform: gpio
    id: blue_led
    pin:
      number: GPIO5
    inverted: true

fan:
  - platform: binary
    id: relay_fan
    name: None
    output: relay_output
    on_turn_on:
      - output.turn_on: blue_led
    on_turn_off:
      - output.turn_off: blue_led

binary_sensor:
  - platform: gpio
    id: relay_button
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    on_click:
      - fan.toggle: relay_fan

status_led:
  id: red_led
  pin:
    number: GPIO4
    inverted: true
