---
# Martin Jerry MJ-S01 Wall Switch - Base Config
# - https://digiblur.com/wiki/devices/switches/martin_jerry_mj-s01_single_pole
# - https://devices.esphome.io/devices/MJ-S01
substitutions:
  click_short: 200ms
  click_double: 350ms
  click_long: 1.25s
  flash_delay: 333ms

globals:
  - id: red_on
    type: bool
    initial_value: 'false'
  - id: blue_on
    type: bool
    initial_value: 'false'

script:
  - id: on_single
    then: {}

  - id: on_double
    then: {}

  - id: on_long
    then: {}

  - id: flash_purple
    then:
      - lambda: |-
          id(red_on) = id(red_led).current_values.is_on();
          id(blue_on) = id(blue_led).current_values.is_on();
      - light.turn_on: red_led
      - light.turn_on: blue_led
      - delay: $flash_delay
      - light.turn_off: red_led
      - light.turn_off: blue_led
      - delay: $flash_delay
      - light.turn_on: red_led
      - light.turn_on: blue_led
      - delay: $flash_delay
      - light.turn_off: red_led
      - light.turn_off: blue_led
      - delay: $flash_delay
      - if:
          condition:
            lambda: 'return id(red_on);'
          then:
            - light.turn_on: red_led
          else:
            - light.turn_off: red_led
      - if:
          condition:
            lambda: 'return id(blue_on);'
          then:
            - light.turn_on: blue_led
          else:
            - light.turn_off: blue_led

esp8266:
  board: esp01_1m

output:
  - platform: gpio
    id: relay_output
    pin: GPIO12

  - platform: gpio
    id: blue_output
    pin:
      number: GPIO5
    inverted: true

binary_sensor:
  - platform: gpio
    id: relay_button
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most $click_long
          - OFF for at least $click_short
        then:
          - script.execute: on_single
      - timing:
          - ON for at most $click_long
          - OFF for at most $click_double
          - ON for at most $click_double
        then:
          - script.execute: on_double
      - timing:
          - ON for at least $click_long
        then:
          - script.execute: on_long

light:
  - platform: status_led
    id: red_led
    pin:
      number: GPIO4
      inverted: true

  - platform: binary
    id: blue_led
    output: blue_output
