# Martin Jerry MJ-S01 Wall Switch (Fan)
# - https://digiblur.com/wiki/devices/switches/martin_jerry_mj-s01_single_pole
# - https://devices.esphome.io/devices/MJ-S01
# - https://templates.blakadder.com/martin-jerry-MJ-S01.html
esp8266:
  board: esp01_1m

output:
  - platform: gpio
    pin: GPIO12
    id: relay_output

  - platform: gpio
    pin:
      number: GPIO5
    inverted: true
    id: blue_led

fan:
  - platform: binary
    name: None
    id: relay_fan
    output: relay_output
    on_turn_on:
      - output.turn_on: blue_led
    on_turn_off:
      - output.turn_off: blue_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
    id: relay_button
    on_press:
      - fan.toggle: relay_fan

status_led:
  pin:
    number: GPIO4
    inverted: true
  id: red_led
