# Sonoff S31 Lite - https://www.esphome-devices.com/devices/Sonoff-S31
esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: Button
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.05s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button

switch:
  - platform: gpio
    pin: GPIO12
    name: Switch
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: true
