# Sonoff S31 Lite
# - https://www.esphome-devices.com/devices/Sonoff-S31
# - https://digiblur.com/wiki/devices/plugs/sonoff_s31
esp8266:
  board: esp01_1m
  early_pin_init: false
  restore_from_flash: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: relay_button
    on_press:
      - light.toggle: relay_light

light:
  - platform: binary
    name: None
    icon: $device_icon
    id: relay_light
    output: relay_output
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: gpio
    pin: GPIO12
    id: relay_output

status_led:
  pin:
    number: GPIO13
    inverted: true
