---
# Sonoff S31 Lite
# - https://www.esphome-devices.com/devices/Sonoff-S31
# - https://digiblur.com/wiki/devices/plugs/sonoff_s31
substitutions:
  click_short: 200ms
  click_double: 333ms
  click_long: 850ms
  flash_delay: 200ms

globals:
  - id: blue_on
    type: bool
    initial_value: 'false'

script:
  - id: on_single
    then: {}

  - id: on_double
    then: {}

  - id: on_long
    then: {}

  - id: flash_blue
    then:
      - lambda: |-
          id(blue_on) = id(blue_led).current_values.is_on();
      - light.turn_on: blue_led
      - delay: $flash_delay
      - light.turn_off: blue_led
      - delay: $flash_delay
      - light.turn_on: blue_led
      - delay: $flash_delay
      - light.turn_off: blue_led
      - delay: $flash_delay
      - if:
          condition:
            lambda: 'return id(blue_on);'
          then:
            - light.turn_on: blue_led
          else:
            - light.turn_off: blue_led

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false

output:
  - platform: gpio
    pin: GPIO12
    id: relay_output

  - platform: gpio
    id: blue_output
    pin:
      number: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    id: the_button
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most $click_long
          - OFF for at least $click_short
        then:
          - script.execute: on_single
      - timing:
          - ON for at most $click_long
          - OFF for at most $click_double
          - ON for at least 1ms
        then:
          - script.execute: on_double
      - timing:
          - ON for at least $click_long
        then:
          - script.execute: on_long

light:
  - platform: binary
    id: blue_led
    output: blue_output
