---
# Sonoff S31 Lite
# - https://www.esphome-devices.com/devices/Sonoff-S31
# - https://digiblur.com/wiki/devices/plugs/sonoff_s31
esp8266:
  board: esp01_1m
  restore_from_flash: true

binary_sensor:
  - platform: gpio
    id: the_button
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    on_click:
      - switch.toggle: relay_switch

switch:
  - platform: gpio
    id: relay_switch
    name: None
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: GPIO13
    inverted: true
