---
# Sonoff S31 Lite (Light)
# - https://www.esphome-devices.com/devices/Sonoff-S31
# - https://digiblur.com/wiki/devices/plugs/sonoff_s31
substitutions:
  device_icon: "mdi:lamp"

esp8266:
  board: esp01_1m

output:
  - platform: gpio
    id: relay_output
    pin: GPIO12

binary_sensor:
  - platform: gpio
    id: the_button
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    on_click:
      - light.toggle: relay_light

light:
  - platform: binary
    id: relay_light
    name: None
    icon: $device_icon
    output: relay_output

status_led:
  pin:
    number: GPIO13
    inverted: true
