# Sonoff S31 - https://www.esphome-devices.com/devices/Sonoff-S31
substitutions:
  sample_rate: "1s"
  update_interval: "30s"

packages:
  parent: !include s31-lite.yaml

logger:
  # Disable UART logging, interferes with cse7766
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
#    current:
#      name: Current
#      id: current
#      filters:
#        - throttle_average: $update_interval
#    voltage:
#      name: Voltage
#      id: voltage
#      filters:
#        - throttle_average: $update_interval
    power:
      name: Power
      id: power
      filters:
        - throttle_average: $update_interval
    update_interval: $sample_rate
  - platform: total_daily_energy
    name: Total Daily Energy
    power_id: power
    unit_of_measurement: kWh
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
#  - platform: template
#    name: Power Factor
#    id: power_factor
#    lambda: return id(power).state / id(voltage).state / id(current).state;
#    accuracy_decimals: 3
#    filters:
#      - throttle_average: $update_interval
#    update_interval: $sample_rate
