---
# Shelly 1 - Light
# - https://www.esphome-devices.com/devices/Shelly-1
esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false

output:
  - platform: gpio
    id: relay_output
    pin: GPIO4

binary_sensor:
  - platform: gpio
    id: the_switch
    pin:
      number: GPIO5
    on_state:
      then:
        - light.toggle: relay_light

light:
  - platform: binary
    id: relay_light
    name: None
    icon: $device_icon
    output: relay_output
    restore_mode: RESTORE_DEFAULT_OFF
