---
# Shelly 1 - Garage Door Opener
# - https://savjee.be/2020/06/make-garage-door-opener-smart-shelly-esphome-home-assistant/
# - https://github.com/athom-tech/athom-configs/blob/main/athom-garage-door.yaml
esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    id: contact_sensor
    pin:
      number: GPIO5
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 50ms

switch:
  - platform: gpio
    id: relay_switch
    pin: GPIO4
    on_turn_on:
      then:
        - delay: 250ms
        - switch.turn_off: relay_switch
    restore_mode: ALWAYS_OFF

cover:
  - platform: template
    name: None
    device_class: garage
    lambda: "return id(contact_sensor).state ? COVER_OPEN : COVER_CLOSED;"
    open_action:
      - switch.turn_on: relay_switch
    close_action:
      - switch.turn_on: relay_switch
    stop_action:
      - switch.turn_on: relay_switch
