---
# Shelly 1 Relay
# - https://www.esphome-devices.com/devices/Shelly-1
esp8266:
  board: esp01_1m

output:
  - platform: gpio
    id: relay_output
    pin: GPIO4

binary_sensor:
  - platform: gpio
    id: the_switch
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
    on_press:
        - light.toggle: relay_light
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: restart_button

light:
  - platform: binary
    id: relay_light
    name: None
    icon: $device_icon
    output: relay_output
