---
# CSE7766 Power Sensor
# - https://esphome.io/components/sensor/cse7766.html
substitutions:
  update_interval_fast: "30s"
  update_interval_slow: "60s"

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

sensor:
  - platform: cse7766
    current:
      id: current
      name: Current
      filters:
        - throttle: $update_interval_fast
        - delta: 0.1
    voltage:
      id: voltage
      name: Voltage
      filters:
        - throttle: $update_interval_slow
        - delta: 0.1
    power:
      id: power
      name: Power
      filters:
        - throttle: $update_interval_fast
        - delta: 0.5

  - platform: total_daily_energy
    name: Total Daily Energy
    power_id: power
    filters:
      - multiply: 0.001
      - throttle: $update_interval_slow
    unit_of_measurement: kWh
