---
# CSE7766 Power Sensor
# - https://esphome.io/components/sensor/cse7766.html
substitutions:
  update_interval: 30s

logger:
  # Disable UART logging, interferes with cse7766
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      id: current
      name: Current
      filters:
        - throttle_average: $update_interval
    voltage:
      id: voltage
      name: Voltage
      filters:
        - throttle_average: $update_interval
    power:
      id: power
      name: Power
      filters:
        - throttle_average: $update_interval
    apparent_power:
      id: apparent_power
      name: "Apparent Power"
      filters:
        - throttle_average: $update_interval
    power_factor:
      id: power_factor
      name: "Power Factor"
      filters:
        - throttle_average: $update_interval

  - platform: total_daily_energy
    name: Total Daily Energy
    power_id: power
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001
