---
# CSE7766 Power Sensor
# - https://esphome.io/components/sensor/cse7766.html
substitutions:
  update_interval_fast: "15s"
  update_interval_slow: "60s"

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

sensor:
  - platform: cse7766
    current:
      id: current
      name: Current
      device_class: current
      state_class: measurement
      filters:
        - or:
          - delta: 0.1
          - throttle_average: $update_interval_fast
        - delta: 0.05
    voltage:
      id: voltage
      name: Voltage
      device_class: voltage
      state_class: measurement
      filters:
        - throttle_average: $update_interval_slow
        - delta: 0.5
    power:
      id: raw_power
      internal: true
      on_value:
        - component.update: power

  - platform: template
    id: power
    name: Power
    state_class: measurement
    device_class: power
    unit_of_measurement: W
    lambda: return id(raw_power).state;
    update_interval: never
    filters:
      - or:
        - delta: 10.0
        - throttle_average: $update_interval_fast
      - delta: 3.0

  - platform: total_daily_energy
    name: Total Daily Energy
    state_class: total_increasing
    power_id: raw_power
    device_class: energy
    method: trapezoid
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001
      - throttle: $update_interval_slow
