---
# CSE7766 Power Sensor
# - https://esphome.io/components/sensor/cse7766.html
substitutions:
  update_interval_fast: "30s"
  update_interval_slow: "60s"

logger:
  # Disable UART logging, interferes with cse7766
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

sensor:
  - platform: cse7766
    current:
      id: current
      name: Current
      filters:
        - throttle_average: $update_interval_fast
    voltage:
      id: voltage
      name: Voltage
      filters:
        - throttle_average: $update_interval_slow
    power:
      id: power
      name: Power
      filters:
        - or:
          - delta: 10%
          - throttle_average: $update_interval_fast
#    apparent_power:
#      id: apparent_power
#      name: "Apparent Power"
#      filters:
#        - or:
#          - delta: 10%
#          - throttle_average: $update_interval_fast
#    power_factor:
#      id: power_factor
#      name: "Power Factor"
#      filters:
#        - or:
#          - delta: 10%
#          - throttle_average: $update_interval_fast

  - platform: total_daily_energy
    name: Total Daily Energy
    power_id: power
    filters:
      - multiply: 0.001
      - throttle: $update_interval_slow
    unit_of_measurement: kWh
