---
# Martin Jerry MJ-S01 - Common Light Config
substitutions:
  light_auto_off_time: 15min

script:
  - id: light_timer
    then:
      - light.turn_on: red_led
      - light.turn_on: relay_light
      - delay: $light_auto_off_time
      - light.turn_off: relay_light

light:
  - platform: binary
    id: relay_light
    name: None
    output: relay_output
    on_turn_on:
      - light.turn_on: blue_led
    on_turn_off:
      - light.turn_off: blue_led
      - light.turn_off: red_led
      - script.stop: light_timer
