---
# Martin Jerry MJ-S01 - Common Bathroom Fan Config
substitutions:
  fan_auto_off_time: 15min
  device_icon: "mdi:fan"

script:
  - id: fan_off_timer
    mode: restart
    then:
      - light.turn_on: red_led
      - delay: $fan_auto_off_time
      - fan.turn_off: relay_fan

fan:
  - platform: binary
    id: relay_fan
    name: None
    icon: $device_icon
    output: relay_output
    on_turn_on:
      then:
        - light.turn_on: blue_led
        - script.execute: fan_off_timer
    on_turn_off:
      then:
        - light.turn_off: blue_led
        - light.turn_off: red_led
        - script.stop: fan_off_timer
    restore_mode: RESTORE_DEFAULT_OFF
