---
# Martin Jerry MJ-S01 - Common Ceiling Fan Config
substitutions:
  device_icon: "mdi:fan"

fan:
  - platform: binary
    id: relay_fan
    name: None
    icon: $device_icon
    output: relay_output
    on_turn_on:
      then:
        - light.turn_on: blue_led
    on_turn_off:
      then:
        - light.turn_off: blue_led
    restore_mode: RESTORE_DEFAULT_OFF
