---
# Martin Jerry MJ-S01 - Common Fan Config
substitutions:
  fan_auto_off_time: 15min

script:
  - id: fan_timer
    mode: restart
    then:
      - light.turn_on: red_led
      - fan.turn_on: relay_fan
      - delay: $fan_auto_off_time
      - fan.turn_off: relay_fan

fan:
  - platform: binary
    id: relay_fan
    name: None
    output: relay_output
    on_turn_on:
      then:
        - light.turn_on: blue_led
    on_turn_off:
      then:
        - light.turn_off: blue_led
        - light.turn_off: red_led
        - script.stop: fan_timer
    restore_mode: RESTORE_DEFAULT_OFF
