---
# Martin Jerry MJ-S01 - Common Light Config
substitutions:
  light_auto_off_time: 15min
  device_icon: "mdi:lightbulb"

script:
  - id: light_off_timer
    mode: restart
    then:
      - light.turn_on: red_led
      - delay: $light_auto_off_time
      - light.turn_off: relay_light

light:
  - platform: binary
    id: relay_light
    name: None
    icon: $device_icon
    output: relay_output
    on_turn_on:
      then:
        - light.turn_on: blue_led
    on_turn_off:
      then:
        - light.turn_off: blue_led
        - light.turn_off: red_led
        - script.stop: light_off_timer
    restore_mode: RESTORE_DEFAULT_OFF
