---
# S31 - Common Light Ronfig
substitutions:
  device_icon: "mdi:lamp"

light:
  - platform: binary
    id: relay_light
    name: None
    icon: $device_icon
    output: relay_output
    restore_mode: RESTORE_DEFAULT_OFF
